language: python
sudo: required
dist: trusty
python: 3.6

install:
  # python
  - pip install -r requirements.txt
  # Install TeXLive
  - curl -sSL https://raw.githubusercontent.com/seisman/install/master/install-texlive.sh -o install-tl.sh
  - sudo bash install-tl.sh
  - curl -sSL https://raw.githubusercontent.com/seisman/install/master/install-SourceCodePro.sh | sudo bash
  - source ~/.bash_profile
  - export TLMGR=`which tlmgr`
  # update texlive
  # - sudo $TLMGR update --self --all -repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/

script:
  - make linkcheck
  # build html and PDF
  - make build


deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: build/html
  on:
    branch: master
